### ISSUE TITLE
Unable to send macros without voice command or keybind

### ISSUE THREAD

**Issue by dalkain** [agaertner/bhm-chat-macros#64]
Absolutely love the redesign and all of the new features! However, it seems a bit of basic functionality has been removed and I'm not sure if something just isn't working on my end.

I can't figure out any way to send a macro other than by assigning a voice command or keybind -- the list of macros no longer appears when clicking the menu button and there is no option in the library pane to send them.

Are there plans to re-add this functionality is is this unexpected behavior?

I'm running Blish HUD v1.1.1 and Chat Shorts v0.9.18

**Comment by agaertner** [comment]
Yes, the list of macros as a dropdown from the corner icon was removed.

I can add such a list back but into its own **thin** window that you can drag around and I will make that window ignore closing with ESC (so you can treat it as a permanent thing on your screen).

I won't add the dropdown on the corner icon back though. It was bad design.
